version: 2.1
# using pipeline variables instead of parameter variables. 
# adding anchor for defaults like docker

defaults: &defaults   ## anchor & aliases
    docker:
      - image: circleci/node:13.8.0

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>

jobs:
  JobCallingCmd:
    <<: *defaults
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>

workflows:
  my_commands:
    jobs:
      - JobCallingCmd