version: 2.1

commands: 
  print_pipeline_id:
    description: "Prints the Circle workflow ID to screen"
    parameters:           ## using caps lock = failure!
      id:
        type: string
    steps:
      - run: echo << parameters.id >>
   #   to:
   #    type: string
   #   default: ${CIRCLE_WORKFLOW_ID}

defaults: &defaults   ## anchor & aliases
    docker:
      - image: circleci/node:13.8.0


jobs:
  print_output_file:
    <<: *defaults
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
  #        to: "add different parameter if wanted"   # if this isn't here it'll use ${CIRCLE_WORKFLOW_ID}

workflows:
  My_Commands:
    jobs:
      - print_output_file